services:
  cloudsaver:
    image: jiangrui1994/cloudsaver:latest
    container_name: cloudsaver
    ports:
      - 24010:8008
    volumes:
      - /share/CACHEDEV1_DATA/Public/Docker/cloudsaver/data:/app/data
      - /share/CACHEDEV1_DATA/Public/Docker/cloudsaver/config:/app/config
    restart: always
    network_mode: bridge
