services:
  emby:
    image: amilys/embyserver:latest
    container_name: embyserver
    privileged: true
    ports:
      - 20015:8096
    volumes:
      - /share/CACHEDEV1_DATA/Public/Docker/emby/config:/config
      - /share/CACHEDEV1_DATA/Public/Video:/data
    restart: always
    network_mode: bridge
