services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    ports:
      - 23000:3000
      - 23001:80
    volumes:
      - /share/CACHEDEV1_DATA/Public/Docker/emulatorjs/config:/config
      - /share/CACHEDEV1_DATA/Public/Docker/emulatorjs/data:/data
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
