services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    ports:
      - 10001:3000
      - 10000:80
    volumes:
      - /vol1/1000/Docker/emulatorjs/config:/config
      - /vol1/1000/Docker/emulatorjs/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
