services:
  firefox:
    image: jlesage/firefox:latest
    container_name: firefox
    ports:
      - 27000:5800
    volumes:
      - /share/CACHEDEV1_DATA/Public/Docker/firefox/config:/config:rw
      - /share/CACHEDEV1_DATA/Public/Docker/firefox/fonts:/usr/share/fonts
      - /share/CACHEDEV1_DATA/Public/Downloads:/config/downloads
    restart: always
    network_mode: bridge
