services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    ports:
      - 25030:8123
    volumes:
      - /share/CACHEDEV1_DATA/Public/Docker/homeassistant:/config
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
