services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - 21000:4533
    volumes:
      - /share/CACHEDEV1_DATA/Public/Docker/navidrome:/data
      - /share/CACHEDEV1_DATA/Public/Music:/music
    restart: always
    network_mode: bridge
