services:
  verysync:
    image: jonnyan404/verysync:latest
    container_name: verysync
    ports:
      - 26010:8886
    volumes:
      - /share/CACHEDEV1_DATA/Public/Synchronous:/data
    restart: always
    network_mode: bridge
