services:
  wallos:
    image: bellamy/wallos:latest
    container_name: wallos
    ports:
      - 25010:80
    volumes:
      - /share/CACHEDEV1_DATA/Public/Docker/wallos/data:/var/www/html/db
      - /share/CACHEDEV1_DATA/Public/Docker/wallos/logos:/var/www/html/images/uploads/logos
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
