services:
  wps-office:
    image: linuxserver/wps-office:chinese
    container_name: wps-office
    ports:
      - 26000:3000
      - 26001:3001
    volumes:
      - /share/CACHEDEV1_DATA/Public/Docker/wps-office/config:/config
      - /share/CACHEDEV1_DATA/Public/Docker/wps-office/Desktop:/config/Desktop
      - /share/CACHEDEV1_DATA/Public/Docker/wps-office/Fonts:/usr/share/fonts/wps-fonts
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Asia/Shanghai
      - CUSTOM_USER=admin
      - PASSWORD=admin
    restart: always
    network_mode: bridge
