services:
  1panel:
    image: koryking/1panel:latest
    container_name: 1panel
    ports:
      - 11000:10086
    volumes:
      - /volume1/My/Docker/1panel:/opt/1panel
      - /volume1/My/:/volume1/My/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - PANEL_BASE_DIR=/opt/1panel
      - PANEL_PORT=10086
      - PANEL_ENTRANCE=123456
      - PANEL_USERNAME=admin
      - PANEL_PASSWORD=password
    network_mode: bridge
    restart: always
