services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    ports:
      - 20025:19035
    volumes:
      - /volume1/My/Docker/chinesesubfinder/config:/config
      - /volume1/My/Docker/chinesesubfinder/cache:/app/cache
      - /volume1/My/Video:/media
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
