services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    ports:
      - 30030:9117
    volumes:
      - /volume1/My/Docker/jackett/config:/config
      - /volume1/My/Docker/jackett/downloads:/downloads
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=false
    restart: always
    network_mode: bridge
