services:
  jellyfin:
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    privileged: true
    devices:
     - /dev/dri:/dev/dri
    ports:
      - 3010:8096
    volumes:
      - /volume1/My/Docker/jellyfin/config:/config
      - /volume1/My/Docker/jellyfin/cache:/cache
      - /volume1/My/Video:/video
    restart: always
    network_mode: bridge
