services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    ports:
      - 22005:25600
    volumes:
      - /volume1/My/Docker/komga/config:/config
      - /volume1/My/Docker/komga/data:/data
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    network_mode: bridge
    restart: always
