services:
  lyricapi:
    image: hisatri/lyricapi:latest
    container_name: lyricapi
    ports:
      - 21010:28883
    volumes:
      - /volume1/My/Music:/music
    restart: always
    network_mode: bridge
