services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 26025:11434
    volumes:
      - /volume1/My/Docker/ollama:/root/.ollama
      - /volume1/My/Docker/ollama/models:/data/models
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
