services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.6.6
    container_name: qbittorrent
    ports:
      - 28000:28000
    volumes:
      - /volume1/My/Docker/qbittorrent:/config
      - /volume1/My/Video:/downloads
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - WEBUI_PORT=28000
    restart: always
    network_mode: bridge
