services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.6.6
    container_name: qbittorrent
    ports:
      - 28000:3020
    volumes:
      - /volume1/My/Docker/qbittorrent:/config
      - /volume1/My/Video:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=3020
    restart: always
    network_mode: bridge
