services:
  reader:
    image: hectorqin/reader:latest
    container_name: reader
    ports:
      - 22000:8080
    volumes:
      - /volume1/My/Docker/reader/log:/log
      - /volume1/My/Docker/reader/storage:/storage
    restart: always
    network_mode: bridge
