services:
  teamspeak:
    image: teamspeak:latest
    container_name: teamspeak
    user: "0:0"
    ports:
      - 23005:9987/udp
      - 23006:30033
      - 23007:41144
      - 23008:10011
    volumes:
      - /volume1/My/Docker/teamspeak:/var/ts3server
    environment:
      - TS3SERVER_DB_PLUGIN=ts3db_postgresql
      - TS3SERVER_DB_SQLCREATEPATH=create_postgresql
      - TS3SERVER_DB_HOST=postgres
      - TS3SERVER_DB_USER=admin
      - TS3SERVER_DB_PASSWORD=password
      - TS3SERVER_DB_NAME=teamspeak
      - TS3SERVER_DB_WAITUNTILREADY=30
      - TS3SERVER_LICENSE=accept
    restart: always
    network_mode: bridge
