services:
  alist-strm:
    image: itefuir/alist-strm:latest
    container_name: alist-strm
    stdin_open: true
    tty: true
    ports:
      - 30050:5000
    volumes:
      - /volume1/@home/Testroot/Docker/alist-strm:/config
      - /volume1/@home/Testroot/Video:/Video
    restart: always
    network_mode: bridge
