services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    ports:
      - 24005:5244
    volumes:
      - /volume1/@home/Testroot/Docker/alist:/opt/alist/data
    environment:
      - PUID=1001
      - PGID=10
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
