services:
  cashbook:
    container_name: cashbook
    image: dingdangdog/cashbook:latest
    ports:
      - 12010:9090
    volumes:
      - /volume1/@home/Testroot/Docker/cashbook/data:/app/data
    environment:
      DATABASE_URL: "postgresql://admin:password@127.0.0.1:5432/cashbook?schema=public"
      NUXT_DATA_PATH: "/app/data"
      NUXT_APP_URL: "https://127.0.0.1:5432"
      NUXT_AUTH_ORIGIN: "https://127.0.0.1:5432/api/auth"
      NUXT_AUTH_SECRET: "auth_secret"
      NUXT_ADMIN_USERNAME: "admin"
      NUXT_ADMIN_PASSWORD: "749f09bade8aca755660eeb17792da880218d4fbdc4e25fbec279d7fe9f65d70"
    restart: always
    network_mode: cashbook
