services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    ports:
      - 20025:19035
    volumes:
      - /volume1/@home/Testroot/Docker/chinesesubfinder/config:/config
      - /volume1/@home/Testroot/Docker/chinesesubfinder/cache:/app/cache
      - /volume1/@home/Testroot/Video:/media
    environment:
      - PUID=1001
      - PGID=10
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
