services:
  emby:
    image: amilys/embyserver:latest
    container_name: embyserver
    privileged: true
    ports:
      - 20015:8096
    volumes:
      - /volume1/@home/Testroot/Docker/emby/config:/config
      - /volume1/@home/Testroot/Video:/data
    restart: always
    network_mode: bridge
