services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    privileged: true
    ports:
      - 10001:3000
      - 10000:80
    volumes:
      - /volume1/@home/Testroot/Docker/emulatorjs/config:/config
      - /volume1/@home/Testroot/Docker/emulatorjs/data:/data
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
