services:
  ezbookkeeping:
    image: mayswind/ezbookkeeping:latest
    container_name: ezbookkeeping
    user: "1001:10"
    ports:
      - 25005:8080
    volumes:
      - /volume1/@home/Testroot/Docker/ezbookkeeping/storage:/ezbookkeeping/storage
      - /volume1/@home/Testroot/Docker/ezbookkeeping/log:/ezbookkeeping/log
      - /etc/localtime:/etc/localtime:ro
    environment:
      - EBK_SERVER_ENABLE_GZIP=true
      - EBK_DATABASE_TYPE=mysql
      - EBK_DATABASE_HOST=127.0.0.1:29000
      - EBK_DATABASE_NAME=ezbookkeeping
      - EBK_DATABASE_USER=root
      - EBK_DATABASE_PASSWD=123456
      - EBK_LOG_MODE=console file
      - EBK_SECURITY_SECRET_KEY=123456
    restart: always
    network_mode: bridge
