services:
  firefox:
    image: jlesage/firefox:latest
    container_name: firefox
    ports:
      - 27000:5800
    volumes:
      - /volume1/@home/Testroot/Docker/firefox/config:/config:rw
      - /volume1/@home/Testroot/Docker/firefox/fonts:/usr/share/fonts
      - /volume1/@home/Testroot/Downloads:/config/downloads
    restart: always
    network_mode: bridge
