services:
  firefox:
    image: jlesage/firefox:latest
    container_name: firefox
    ports:
      - 27000:5800
    volumes:
      - /vol1/1000/Docker/firefox/config:/config:rw
      - /vol1/1000/Docker/firefox/fonts:/usr/share/fonts
      - /vol1/1000/Downloads:/config/downloads
    environment:
      - PUID=1000
      - PGID=10
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
