services:
  iptv-api:
    image: guovern/iptv-api:latest
    container_name: iptv-api
    ports:
      - 3055:8000
    volumes:
      - /volume1/@home/Testroot/Docker/iptv-api/config:/iptv-api/config
      - /volume1/@home/Testroot/Docker/iptv-api/output:/iptv-api/output
    restart: always
    network_mode: bridge
