services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    ports:
      - 22005:25600
    volumes:
      - /volume1/@home/Testroot/Docker/komga/config:/config
      - /volume1/@home/Testroot/Docker/komga/data:/data
    environment:
      - PUID=1001
      - PGID=10
      - TZ=Asia/Shanghai
    network_mode: bridge
    restart: always
