services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    user: "0:0"
    ports:
      - 29010:3306
    volumes:
      - /volume1/@home/Testroot/Docker/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    restart: always
    network_mode: bridge
