services:
  mtphotos:
    image: registry.cn-hangzhou.aliyuncs.com/mtphotos/mt-photos:latest
    container_name: mtphotos
    ports:
      - 25035:8063
    volumes:
      - /volume1/@home/Testroot/Docker/mtphotos/config:/config
      - /volume1/@home/Testroot/Docker/mtphotos/upload:/upload
      - /volume1/@home/Testroot/Photos:/photos
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    dns:
      - 114.114.114.114
    depends_on:
      - mtphotos_ai
      - mtphotos_face_api
    restart: always
    network_mode: bridge

  mtphotos_ai:
    image: registry.cn-hangzhou.aliyuncs.com/mtphotos/mt-photos-ai:onnx-latest
    container_name: mtphotos_ai
    ports:
      - 25036:8060
    environment:
      - API_AUTH_KEY=mt_photos_ai_extra
    restart: always
    network_mode: bridge

  mtphotos_face_api:
    image: crpi-gcuyquw9co62xzjn.cn-guangzhou.personal.cr.aliyuncs.com/devfox101/mt-photos-insightface-unofficial:latest
    container_name: mtphotos_face_api
    ports:
      - 25037:8066
    environment:
      - API_AUTH_KEY=mt_photos_ai_extra
    restart: always
    network_mode: bridge
