services:
  nastools:
    image: hsuyelin/nas-tools:latest
    container_name: nastools
    ports:
      - 20000:3000
    volumes:
      - /volume1/@home/Testroot/Docker/nastools:/config
      - /volume1/@home/Testroot/Video:/downloads
    environment:
      - PUID=1001
      - PGID=10
      - UMASK=022
      - NASTOOL_AUTO_UPDATE=false
      - NASTOOL_CN_UPDATE=false
      - REPO_URL=https://ghproxy.com/https://github.com/hsuyelin/nas-tools.git
    restart: always
    network_mode: bridge
