services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.6.6
    container_name: qbittorrent
    ports:
      - 28000:28000
    volumes:
      - /volume1/@home/Testroot/Docker/qbittorrent:/config
      - /volume1/@home/Testroot/Video:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=28000
    restart: always
    network_mode: bridge
