services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: pdftool
    ports:
      - 7020:8080
    volumes:
      - /volume1/@home/Testroot/Docker/pdftool/trainingData:/usr/share/tessdata
      - /volume1/@home/Testroot/Docker/pdftool/extraConfigs:/configs
      - /volume1/@home/Testroot/Docker/pdftool/customFiles:/customFiles/
      - /volume1/@home/Testroot/Docker/pdftool/logs:/logs/
      - /volume1/@home/Testroot/Docker/pdftool/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
    restart: always
    network_mode: bridge
