services:
  synctv:
    image: synctvorg/synctv:latest
    container_name: synctv
    ports:
      - 20040:8080
    volumes:
      - /volume1/@home/Testroot/Docker/synctv:/root/.synctv
    restart: always
    network_mode: bridge
