services:
  taoSync:
    image: dr34m/tao-sync:latest
    container_name: taoSync
    ports:
      - 30045:8023
    volumes:
      - /volume1/@home/Testroot/Docker/taoSync:/app/data
    restart: always
    network_mode: bridge
