services:
  teamspeak:
    image: teamspeak:latest
    container_name: teamspeak
    privileged: true
    ports:
      - 23005:9987/udp
      - 23006:30033
      - 23007:41144
      - 23008:10011
    volumes:
      - /volume1/@home/Testroot/Docker/teamspeak:/var/ts3server
    environment:
      - TS3SERVER_DB_PLUGIN=ts3db_mariadb
      - TS3SERVER_DB_SQLCREATEPATH=create_mariadb
      - TS3SERVER_DB_HOST=mariadb
      - TS3SERVER_DB_USER=root
      - TS3SERVER_DB_PASSWORD=123456
      - TS3SERVER_DB_NAME=teamspeak
      - TS3SERVER_DB_WAITUNTILREADY=30
      - TS3SERVER_LICENSE=accept
    restart: always
    network_mode: bridge
