services:
  transmission:
    image: linuxserver/transmission:4.0.5
    container_name: transmission
    ports:
      - 3025:9091
    volumes:
      - /volume1/@home/Testroot/Docker/transmission:/config
      - /volume1/@home/Testroot/Video:/downloads
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/config/webui/Transmission Theme
      - USER=root
      - PASS=root
    restart: always
    network_mode: bridge
