services:
  v2raya:
    image: v2raya/v2raya:latest
    container_name: v2raya
    privileged: true
    ports:
      - 8020:2017
    volumes:
      - /volume1/@home/Testroot/Docker/v2raya:/etc/v2raya
    restart: always
    network_mode: bridge
