services:
  vertex:
    image: lswl/vertex:latest
    container_name: vertex
    ports:
      - 30020:32110
    volumes:
      - /volume1/@home/Testroot/Docker/vertex:/vertex
    environment:
      - PORT=32110
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
