services:
  wallos:
    image: bellamy/wallos:latest
    container_name: wallos
    ports:
      - 12000:80
    volumes:
      - /volume1/@home/Testroot/Docker/wallos/data:/var/www/html/db
      - /volume1/@home/Testroot/Docker/wallos/logos:/var/www/html/images/uploads/logos
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
