services:
  aipan:
    image: unilei/aipan-netdisk-search-simple:latest
    container_name: aipan
    ports:
      - 24000:3000
    environment:
      - NUXT_HOST="0.0.0.0"
      - NUXT_PORT=3000
    restart: always
    network_mode: bridge
