services:
  iptv-api:
    image: guovern/iptv-api:latest
    container_name: iptv-api
    ports:
      - 20020:8000
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/iptv-api/config:/iptv-api/config
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/iptv-api/output:/iptv-api/output
    restart: always
    network_mode: bridge
