services:
  istoreos:
    image: fingerboy/istoreos-x86-64:latest
    container_name: istoreos
    privileged: true
    command: /sbin/init
    restart: always
    networks:
      macnet:
        ipv4_address: 127.0.0.1
networks:
  macnet:
    external: true
