services:
  lucky:
    image: gdy666/lucky:latest
    container_name: lucky
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/lucky:/goodluck
    restart: always
    network_mode: host
