services:
  lyricapi:
    image: hisatri/lyricapi:latest
    container_name: lyricapi
    ports:
      - 21010:28883
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Music:/music
    restart: always
    network_mode: bridge
