services:
  mediago:
    image: registry.cn-beijing.aliyuncs.com/caorushizi/mediago:latest
    container_name: mediago
    ports:
      - 28015:8899
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Downloads:/root/mediago
    restart: always
    network_mode: bridge
