services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - 21000:4533
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/navidrome:/data
      - /var/lib/casaos_data/.media/SSD-Storage/Music:/music
    restart: always
    network_mode: bridge
