services:
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    ports:
      - 30015:5700
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/qinglong:/ql/data
    environment:
      - QlPort=5700
    restart: always
    network_mode: bridge
