services:
  synctv:
    image: synctvorg/synctv:latest
    container_name: synctv
    ports:
      - 20040:8080
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/synctv:/root/.synctv
    restart: always
    network_mode: bridge
