services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    environment:
      - TS_AUTHKEY=密钥
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ROUTES=127.0.0.1/24
    restart: always
    network_mode: host
