services:
  verysync:
    image: jonnyan404/verysync:latest
    container_name: verysync
    ports:
      - 26010:8886
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Synchronous:/data
    restart: always
    network_mode: bridge
