services:
  wps-office:
    image: linuxserver/wps-office:chinese
    container_name: wps-office
    ports:
      - 26000:3000
      - 26001:3001
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/wps-office/config:/config
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/wps-office/Desktop:/config/Desktop
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/wps-office/Fonts:/usr/share/fonts/wps-fonts
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Shanghai
      - CUSTOM_USER=admin
      - PASSWORD=admin
    restart: always
    network_mode: bridge
