services:
  zerotier:
    image: zerotier/zerotier:latest
    container_name: zerotier
    privileged: true
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/zerotier:/var/lib/zerotier-one
    restart: always
    network_mode: host
