services:

  moviepilot:
    image: jxxghp/moviepilot-v2:latest
    container_name: moviepilot
    ports:
      - 20005:3000
    volumes:
      - /vol1/1000/Video:/downloads
      - /vol1/1000/Docker/moviepilot:/config
    environment:
      - NGINX_PORT=3000
      - PORT=3001
      - PUID=1000
      - PGID=1001
      - UMASK=000
      - TZ=Asia/Shanghai
      - SUPERUSER=admin
    restart: always
    network_mode: bridge

  jellyfin:
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 20010:8096
    volumes:
      - /vol1/1000/Docker/jellyfin/config:/config
      - /vol1/1000/Docker/jellyfin/cache:/cache
      - /vol1/1000/Video:/video
    restart: always
    network_mode: bridge

  iptv-api:
    image: guovern/iptv-api:latest
    container_name: iptv-api
    ports:
      - 20020:8000
    volumes:
      - /vol1/1000/Docker/iptv-api/config:/iptv-api/config
      - /vol1/1000/Docker/iptv-api/output:/iptv-api/output
    restart: always
    network_mode: bridge

  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    ports:
      - 20025:19035
    volumes:
      - /vol1/1000/Docker/chinesesubfinder/config:/config
      - /vol1/1000/Docker/chinesesubfinder/cache:/app/cache
      - /vol1/1000/Video:/media
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge

  metatube:
    image: ghcr.io/metatube-community/metatube-server:latest
    container_name: metatube
    ports:
      - 20030:8080
    environment:
      - PORT=8080
      - DB_MAX_IDLE_CONNS=0
      - DB_MAX_OPEN_CONNS=0
      - DB_PREPARED_STMT=0
      - DB_AUTO_MIGRATE=0
    restart: always
    network_mode: bridge

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - 21000:4533
    volumes:
      - /vol1/1000/Docker/navidrome:/data
      - /vol1/1000/Music:/music
    restart: always
    network_mode: bridge

  music-tag-web:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    ports:
      - 21005:8001
    volumes:
      - /vol1/1000/Music:/app/media
      - /vol1/1000/Docker/music-tag-web:/app/data
    restart: always
    network_mode: bridge

  reader:
    image: hectorqin/reader:latest
    container_name: reader
    ports:
      - 22000:8080
    volumes:
      - /vol1/1000/Docker/reader/log:/log
      - /vol1/1000/Docker/reader/storage:/storage
    restart: always
    network_mode: bridge

  komga:
    image: gotson/komga:latest
    container_name: komga
    ports:
      - 22005:25600
    volumes:
      - /vol1/1000/Docker/komga/config:/config
      - /vol1/1000/Docker/komga/data:/data
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Shanghai
    network_mode: bridge
    restart: always

  aipan:
    image: unilei/aipan-netdisk-search-simple:latest
    container_name: aipan
    ports:
      - 24000:3000
    environment:
      - NUXT_HOST="0.0.0.0"
      - NUXT_PORT=3000
    restart: always
    network_mode: bridge

  alist:
    image: xhofe/alist:latest
    container_name: alist
    ports:
      - 24005:5244
    volumes:
      - /vol1/1000/Docker/alist:/opt/alist/data
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge

  cloudsaver:
    image: jiangrui1994/cloudsaver:latest
    container_name: cloudsaver
    ports:
      - 24010:8008
    volumes:
      - /vol1/1000/Docker/cloudsaver/data:/app/data
      - /vol1/1000/Docker/cloudsaver/config:/app/config
    restart: always
    network_mode: bridge

  clouddrive2:
    image: cloudnas/clouddrive2:latest
    container_name: clouddrive2
    privileged: true
    ports:
      - 24015:19798
    volumes:
      - /vol1/1000/Docker/clouddrive2:/Config
      - /vol1/1000/Cloud:/CloudNAS:shared
      - /vol1/1000/Video:/media:shared
    environment:
      - TZ=Asia/Shanghai
      - CLOUDDRIVE_HOME=/Config
    restart: always
    network_mode: bridge

  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    ports:
      - 25030:8123
    volumes:
      - /vol1/1000/Docker/homeassistant:/config
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge

  verysync:
    image: jonnyan404/verysync:latest
    container_name: verysync
    ports:
      - 26010:8886
    volumes:
      - /vol1/1000/Synchronous:/data
    restart: always
    network_mode: bridge

  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - 26015:8080
    volumes:
      - /vol1/1000/Docker/stirling-pdf/trainingData:/usr/share/tessdata
      - /vol1/1000/Docker/stirling-pdf/extraConfigs:/configs
      - /vol1/1000/Docker/stirling-pdf/customFiles:/customFiles/
      - /vol1/1000/Docker/stirling-pdf/logs:/logs/
      - /vol1/1000/Docker/stirling-pdf/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
    restart: always
    network_mode: bridge

  kkfileview:
    image: pi4k8s/kkfileview:4.4.0
    container_name: kkfileview
    ports:
      - 26020:8012
    volumes:
      - /vol1/1000/Docker/kkfileview:/opt/kkFileView-4.4.0
    environment:
      - KK_OFFICE_PREVIEW_TYPE=pdf
      - KK_OFFICE_PREVIEW_SWITCH_DISABLED=true
      - KK_PDF_DOWNLOAD_DISABLE=true
      - KK_FILE_UPLOAD_ENABLED=false
      - KK_CONTEXT_PATH=/
    restart: always
    network_mode: bridge

  siyuan-note-unlock:
    image: apkdv/siyuan-unlock:latest
    container_name: siyuan-note-unlock
    ports:
      - 26035:6806
    command:
      - --workspace=/siyuan/workspace/
      - --accessAuthCode=100
    volumes:
      - /vol1/1000/Docker/siyuan-note-unlock:/siyuan/workspace
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=022
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
    restart: always
    network_mode: bridge

  firefox:
    image: jlesage/firefox:latest
    container_name: firefox
    ports:
      - 27000:5800
    volumes:
      - /vol1/1000/Docker/firefox/config:/config:rw
      - /vol1/1000/Docker/firefox/fonts:/usr/share/fonts
      - /vol1/1000/Downloads:/config/downloads
    environment:
      - USER_ID=1000
      - GROUP_ID=1001
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge

  ip-tool:
    image: jason5ng32/myip:latest
    container_name: ip-tool
    ports:
      - 27005:18966
    restart: always
    network_mode: bridge

  qbittorrent:
    image: linuxserver/qbittorrent:4.6.6
    container_name: qbittorrent
    ports:
      - 28000:28000
    volumes:
      - /vol1/1000/Docker/qbittorrent:/config
      - /vol1/1000/Video:/downloads
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Shanghai
      - WEBUI_PORT=28000
    restart: always
    network_mode: bridge

  transmission:
    image: linuxserver/transmission:4.0.5
    container_name: transmission
    ports:
      - 28005:9091
    volumes:
      - /vol1/1000/Docker/transmission:/config
      - /vol1/1000/Video:/downloads
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/config/webui/Transmission Theme
      - USER=root
      - PASS=root
    restart: always
    network_mode: bridge

  xunlei:
    image: cnk3x/xunlei:latest
    container_name: xunlei
    privileged: true
    ports:
      - 28010:2345
    volumes:
      - /vol1/1000/Docker/xunlei:/xunlei/data
      - /vol1/1000/Downloads:/xunlei/downloads
    environment:
      - XL_GID=0
      - XL_UID=0
      - TZ=Asia/Shanghai
      - XL_DASHBOARD_USERNAME=admin
      - XL_DASHBOARD_PASSWORD=admin
    restart: always
    network_mode: bridge

  mediago:
    image: registry.cn-beijing.aliyuncs.com/caorushizi/mediago:latest
    container_name: mediago
    ports:
      - 28015:8899
    volumes:
      - /vol1/1000/Downloads:/root/mediago
    restart: always
    network_mode: bridge

  iyuuplus:
    image: iyuucn/iyuuplus:latest
    container_name: iyuuplus
    ports:
      - 30000:8780
    volumes:
      - /vol1/1000/Docker/iyuuplus/iyuu:/iyuu
      - /vol1/1000/Docker/iyuuplus/data:/data
      - /vol1/1000/Docker/qbittorrent/qBittorrent/BT_backup:/qb
      - /vol1/1000/Docker/transmission/torrents:/tr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge

  sun-panel:
    image: hslr/sun-panel:latest
    container_name: sun-panel
    ports:
      - 30005:3002
    volumes:
      - /vol1/1000/Docker/sun-panel:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    network_mode: bridge

  1panel:
    image: koryking/1panel:latest
    container_name: 1panel
    ports:
      - 30010:10086
    volumes:
      - /vol1/1000/Docker/1panel:/opt/1panel
      - /vol1/1000/:/vol1/1000/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - PANEL_BASE_DIR=/opt/1panel
      - PANEL_PORT=10086
      - PANEL_ENTRANCE=123456
      - PANEL_USERNAME=admin
      - PANEL_PASSWORD=password
    network_mode: bridge
    restart: always

  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    ports:
      - 30015:5700
    volumes:
      - /vol1/1000/Docker/qinglong:/ql/data
    environment:
      - QlPort=5700
    restart: always
    network_mode: bridge

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_RUN_ONCE=true
      - TZ=Asia/Shanghai
    restart: always
    command: --schedule "0 0 20 * * 0" --cleanup
