services:
  babybuddy:
    image: linuxserver/babybuddy:latest
    container_name: babybuddy
    ports:
      - 8520:8000
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/babybuddy:/config
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
