services:
  bitmagnet:
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    container_name: bitmagnet
    ports:
      - 30090:3333
      - 30091:3334/tcp
      - 30091:3334/udp
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bitmagnet
      - TMDB_API_KEY=846bba4db8f61e718e923c613dafffc2  # TMDB API密钥
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/bitmagnet/config:/root/.config/bitmagnet
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: bitmagnet-postgres
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/postgres:/var/lib/postgresql/data
    ports:
      - 29005:5432
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bitmagnet
    shm_size: 1g
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      start_period: 20s
      interval: 10s
