services:
  clouddrive2:
    image: cloudnas/clouddrive2:latest
    container_name: clouddrive2
    privileged: true
    ports:
      - 3075:19798
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/clouddrive2:/Config
      - /tmp/zfsv3/sata11/13051661743/data/Cloud:/CloudNAS:shared
      - /tmp/zfsv3/sata11/13051661743/data/Video:/media:shared
    environment:
      - TZ=Asia/Shanghai
      - CLOUDDRIVE_HOME=/Config
    restart: always
    network_mode: bridge
