services:
  dpanel:
    image: dpanel/dpanel:latest
    container_name: dpanel
    ports:
      - 30060:8080
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/dpanel:/dpanel
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    network_mode: bridge
