services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    ports:
      - 23000:3000
      - 23001:80
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/emulatorjs/config:/config
      - /tmp/zfsv3/sata11/13051661743/data/Docker/emulatorjs/data:/data
    environment:
      - PUID=1016
      - PGID=1017
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
