services:
  emulatorjs:
    image: linuxserver/emulatorjs:latest
    container_name: emulatorjs
    ports:
      - 10001:3000
      - 10000:80
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/emulatorjs/config:/config
      - /tmp/zfsv3/sata11/13051661743/data/Docker/emulatorjs/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
