services:
  iyuuplus:
    image: iyuucn/iyuuplus:latest
    container_name: iyuuplus
    ports:
      - 30000:8780
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/iyuuplus/iyuu:/iyuu
      - /tmp/zfsv3/sata11/13051661743/data/Docker/iyuuplus/data:/data
      - /tmp/zfsv3/sata11/13051661743/data/Docker/qbittorrent/qBittorrent/BT_backup:/qb
      - /tmp/zfsv3/sata11/13051661743/data/Docker/transmission/torrents:/tr
    environment:
      - PUID=1016
      - PGID=1017
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
