services:
  jellyfin-library-poster:
    image: evanqu/jellyfin-library-poster:latest
    container_name: jellyfin-library-poster
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/jellyfin-library-poster/config:/app/config
      - /tmp/zfsv3/sata11/13051661743/data/Docker/jellyfin-library-poster/poster:/app/poster
      - /tmp/zfsv3/sata11/13051661743/data/Docker/jellyfin-library-poster/output:/app/output
      - /tmp/zfsv3/sata11/13051661743/data/Docker/jellyfin-library-poster/logs:/app/logs
      - /tmp/zfsv3/sata11/13051661743/data/Docker/jellyfin-library-poster/myfont:/app/myfont
    restart: always
    network_mode: bridge
