services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    ports:
      - 22010:25600
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/komga/config:/config
      - /tmp/zfsv3/sata11/13051661743/data/Docker/komga/data:/data
    environment:
      - PUID=1016
      - PGID=1017
      - TZ=Asia/Shanghai
    network_mode: bridge
    restart: always
