services:
  mdcx:
    image: stainless403/mdcx-builtin-gui-base:latest
    container_name: mdcx
    ports:
      - 20045:5800
      - 20046:5900
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/mdcx/config:/config
      - /tmp/zfsv3/sata11/13051661743/data/Docker/mdcx/mdcx-config:/mdcx-config
      - /tmp/zfsv3/sata11/13051661743/data/Docker/mdcx/logs:/app/log
      - /tmp/zfsv3/sata11/13051661743/data/Video:/data
    environment:
      - USER_ID=1016
      - GROUP_ID=1017
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
