services:
  music-tag-web:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    ports:
      - 21005:8001
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Music:/app/media
      - /tmp/zfsv3/sata11/13051661743/data/Docker/music-tag-web:/app/data
    restart: always
    network_mode: bridge
