services:
  npc:
    image: yisier1/npc:latest
    container_name: npc
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/npc:/conf
    command: -server=127.0.0.1:8024 -vkey=自行填写密钥 -type=tcp
    restart: always
    network_mode: host   
