services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/ollama:/root/.ollama
      - /tmp/zfsv3/sata11/13051661743/data/Docker/ollama/models:/data/models
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge    
