services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 11030:5432
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    restart: always
    network_mode: bridge
