services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.6.6
    container_name: qbittorrent
    ports:
      - 28000:28000
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/qbittorrent:/config
      - /tmp/zfsv3/sata11/13051661743/data/Video:/downloads
    environment:
      - PUID=1016
      - PGID=1017
      - TZ=Asia/Shanghai
      - WEBUI_PORT=28000
    restart: always
    network_mode: bridge
