services:
  qiandao:
    image: qdtoday/qd:latest
    container_name: qiandao
    ports:
      - 30035:80
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/qiandao/:/usr/src/app/config
    restart: always
    network_mode: bridge
