services:
  rustdesk-server:
    image: rustdesk/rustdesk-server-s6:latest
    container_name: rustdesk-server
    ports:
      - 30065:21115
      - 30066:21116
      - 30066:21116/udp
      - 30067:21117
      - 30068:21118
      - 30069:21119
    environment:
      - RELAY=域名:端口
      - ENCRYPTED_ONLY=1
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/rustdesk:/data
    restart: always
    network_mode: bridge
