services:
  teamspeak:
    image: teamspeak:latest
    container_name: teamspeak
    ports:
      - 10010:9987/udp
      - 30033:30033
      - 41144:41144
      - 10011:10011
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/teamspeak:/var/ts3server
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: mariadb
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: 123456
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    restart: always
    network_mode: teamspeak
