services:
  transmission:
    image: linuxserver/transmission:4.0.5
    container_name: transmission
    ports:
      - 28005:9091
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/transmission:/config
      - /tmp/zfsv3/sata11/13051661743/data/Video:/downloads
    environment:
      - PUID=1016
      - PGID=1017
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/config/webui/Transmission Theme
      - USER=root
      - PASS=root
    restart: always
    network_mode: bridge
