services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
    # - WATCHTOWER_RUN_ONCE=true
    - TZ=Asia/Shanghai
    restart: always
    command: --schedule "0 0 20 * * 0" --cleanup
