services:
  zerotier:
    image: zerotier/zerotier:latest
    container_name: zerotier
    privileged: true
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/zerotier:/var/lib/zerotier-one
    restart: always
    network_mode: host
