services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    ports:
      - 30040:5001
    volumes:
      - /mnt/test/Docker/dockge/data:/app/data
      - /mnt/test/Docker/dockge:/home/stacks
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    network_mode: bridge
