services:
  firefox:
    image: jlesage/firefox:latest
    container_name: firefox
    ports:
      - 27000:5800
    volumes:
      - /mnt/test/Docker/firefox/config:/config:rw
      - /mnt/test/Docker/firefox/fonts:/usr/share/fonts
      - /mnt/test/Downloads:/config/downloads
    environment:
      - USER_ID=1000
      - GROUP_ID=1001
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
