services:
  icloudpd:
    image: icloudpd/icloudpd:latest
    container_name: icloudpd
    tty: true
    ports:
      - 24020:8080
    volumes:
      - /mnt/test/Photos:/data
    environment:
      - TZ=Asia/Shanghai
    command: icloudpd --directory /data --username youemail@xx.xx --mfa-provider webui --domain cn --password-provider webui --watch-with-interval 3600
    restart: always
    network_mode: bridge
