services:
  qiandao:
    image: qdtoday/qd:latest
    container_name: qiandao
    ports:
      - 30035:80
    volumes:
      - /mnt/test/Docker/qiandao/:/usr/src/app/config
    restart: always
    network_mode: bridge
