services:
  xunlei:
    image: cnk3x/xunlei:latest
    container_name: xunlei
    privileged: true
    ports:
      - 28010:2345
    volumes:
      - /mnt/test/Docker/xunlei:/xunlei/data
      - /mnt/test/Downloads:/xunlei/downloads
    environment:
      - XL_GID=0
      - XL_UID=0
      - TZ=Asia/Shanghai
      - XL_DASHBOARD_USERNAME=admin
      - XL_DASHBOARD_PASSWORD=admin
    restart: always
    network_mode: bridge
