services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    ports:
      - 7050:5244
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/alist:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
