services:
  frpc:
    image: snowdreamtech/frpc
    container_name: frpc
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Frpc:/etc/frp
    command: -c /etc/frp/frpc.ini
    restart: always
    network_mode: host
