services:
  iptv-api:
    image: guovern/iptv-api:latest
    container_name: iptv-api
    ports:
      - 3055:8000
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/iptv-api/config:/iptv-api/config
      - /mnt/dm-1/.ugreen_nas/509155/Docker/iptv-api/output:/iptv-api/output
    restart: always
    network_mode: bridge
