services:
  jellyfin:
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    privileged: true
    devices:
     - /dev/dri:/dev/dri
    ports:
      - 3010:8096
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/jellyfin/config:/config
      - /mnt/dm-1/.ugreen_nas/509155/Docker/jellyfin/cache:/cache
      - /mnt/dm-1/.ugreen_nas/509155/Video:/video
    restart: always
    network_mode: bridge
