services:
  kkfileview:
    image: pi4k8s/kkfileview:4.4.0
    container_name: kkfileview
    ports:
    - 7030:8012
    volumes:
       - /mnt/dm-1/.ugreen_nas/509155/Docker/kkfileview:/opt/kkFileView-4.4.0
    environment:
      - KK_OFFICE_PREVIEW_TYPE=pdf
      - KK_OFFICE_PREVIEW_SWITCH_DISABLED=true
      - KK_PDF_DOWNLOAD_DISABLE=true
      - KK_FILE_UPLOAD_ENABLED=false
      - KK_CONTEXT_PATH=/
    restart: always
    network_mode: bridge
