services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - 4000:4533
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/navidrome:/data
      - /mnt/dm-1/.ugreen_nas/509155/Music:/music
    restart: always
    network_mode: bridge
