services:
  verysync:
    image: jonnyan404/verysync:latest
    container_name: verysync
    ports:
      - 7010:8886
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Synchronous:/data
    restart: always
    network_mode: bridge
