services:
  babybuddy:
    image: linuxserver/babybuddy:latest
    container_name: babybuddy
    ports:
      - 25020:8000
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/babybuddy:/config
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
