services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    ports:
      - 20025:19035
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/chinesesubfinder/config:/config
      - /mnt/dm-1/.ugreen_nas/509155/Docker/chinesesubfinder/cache:/app/cache
      - /mnt/dm-1/.ugreen_nas/509155/Video:/media
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
