services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    ports:
      - 23000:3000
      - 23001:80
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/emulatorjs/config:/config
      - /mnt/dm-1/.ugreen_nas/509155/Docker/emulatorjs/data:/data
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
