services:
  lyricapi:
    image: hisatri/lyricapi:latest
    container_name: lyricapi
    ports:
      - 21010:28883
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Music:/music
    restart: always
    network_mode: bridge
