services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 29010:3306
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    restart: always
    network_mode: bridge
