services:
  mediago:
    image: registry.cn-beijing.aliyuncs.com/caorushizi/mediago:latest
    container_name: mediago
    ports:
      - 28015:8899
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Downloads:/root/mediago
    restart: always
    network_mode: bridge
