services:
  nastool:
    image: hsuyelin/nas-tools:latest
    container_name: nastool
    ports:
      - 20000:3000
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/nastool:/config
      - /mnt/dm-1/.ugreen_nas/509155/Video:/downloads
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=022
      - NASTOOL_AUTO_UPDATE=false
      - NASTOOL_CN_UPDATE=false
      - REPO_URL=https://ghproxy.com/https://github.com/hsuyelin/nas-tools.git
    restart: always
    network_mode: bridge
