services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    ports:
      - 30080:80
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/vaultwarden:/data
    environment:
      - DOMAIN=https://vaultwarden.example.com
      - SIGNUPS_ALLOWED=true
    restart: always
    network_mode: bridge
