services:
  vscode:
    image: linuxserver/code-server:latest
    container_name: vscode
    ports:
      - 30055:8443
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/vscode:/config
    environment:
      - TZ=Asia/Shanghai
      - PASSWORD=password
    restart: always
    network_mode: bridge
