services:
  babybuddy:
    image: linuxserver/babybuddy:latest
    container_name: babybuddy
    ports:
      - 8520:8000
    volumes:
      - /vol1/1000/Docker/babybuddy:/config
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
