services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    ports:
      - 11020:8123
    volumes:
      - /vol1/1000/Docker/homeassistant:/config
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
