services:
  iyuuplus:
    image: iyuucn/iyuuplus:latest
    container_name: iyuuplus
    ports:
      - 30000:8780
    volumes:
      - /vol1/1000/Docker/iyuuplus/iyuu:/iyuu
      - /vol1/1000/Docker/iyuuplus/data:/data
      - /vol1/1000/Docker/qbittorrent/qBittorrent/BT_backup:/qb
      - /vol1/1000/Docker/transmission/torrents:/tr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
