services:
  lsky-pro:
    container_name: lsky-pro
    image: dko0/lsky-pro:latest
    ports:
      - 26040:80
    volumes:
      - /vol1/1000/Docker/lsky-pro:/var/www/html
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=lsky-pro
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    restart: always
    network_mode: bridge
