services:
  mediago:
    image: registry.cn-beijing.aliyuncs.com/caorushizi/mediago:latest
    container_name: mediago
    ports:
      - 8899:8899
    volumes:
      - /vol1/1000/Downloads:/root/mediago
    restart: always
    network_mode: bridge
