services:
  nastool:
    image: hsuyelin/nas-tools:latest
    container_name: nastool
    ports:
      - 20000:3000
    volumes:
      - /vol1/1000/Docker/nastool:/config
      - /vol1/1000/Video:/downloads
    environment:
      - PUID=0
      - PGID=0
      - UMASK=000
      - NASTOOL_AUTO_UPDATE=false
      - NASTOOL_CN_UPDATE=false
      - REPO_URL="https://ghproxy.com/https://github.com/hsuyelin/nas-tools.git"
    restart: always
    network_mode: bridge
