services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - 4000:4533
    volumes:
      - /vol1/1000/Docker/navidrome:/data
      - /vol1/1000/Music:/music
    restart: always
    network_mode: bridge
