services:
  newsnow:
    image: ghcr.io/ourongxing/newsnow:latest
    container_name: newsnow
    ports:
      - 7060:4444
    environment:
      - INIT_TABLE=true
      - ENABLE_CACHE=true
    network_mode: bridge
    restart: always
