services:
  reader:
    image: hectorqin/reader:latest
    container_name: reader
    ports:
      - 5000:8080
    volumes:
      - /vol1/1000/Docker/reader/log:/log
      - /vol1/1000/Docker/reader/storage:/storage
    restart: always
    network_mode: bridge
