services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - 26015:8080
    volumes:
      - /vol1/1000/Docker/stirling-pdf/trainingData:/usr/share/tessdata
      - /vol1/1000/Docker/stirling-pdf/extraConfigs:/configs
      - /vol1/1000/Docker/stirling-pdf/customFiles:/customFiles/
      - /vol1/1000/Docker/stirling-pdf/logs:/logs/
      - /vol1/1000/Docker/stirling-pdf/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
    restart: always
    network_mode: bridge
